version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: wattpaddb
      POSTGRES_USER: equipojyp
      POSTGRES_PASSWORD: p2709j0905
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
