# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: p2709j0905
      POSTGRES_DB: wattpaddb
      POSTGRES_USER: equipojp
    ports: 
      - "5432:5432"

volumes:
  postgres_data: